### PR TITLE
Support conda

### PR DESCRIPTION
**Pull request by NielsZeilemaker**
Implements support for #58. 
It currently requires a conda installation to work.

### CODE REVIEW

**Comment by NielsZeilemaker** [comment]
Seems to be ready, let me know if anyone has any comments. I'll incorporate them into the pull request

**Comment by NielsZeilemaker** [comment]
Hi All, 
Is there something I could do to get this pull request merged?

**Comment by sesh** [comment]
@NielsZeilemaker unfortunately I don't use Conda, so this has been (somewhat) low on my list. I'm going to try get some time over the next week or so to set up a conda env. and test this one!

Thanks so much for your hard work - your contribution is really appreciated and I'm sure this will be super-beneficial for the Conda community.

**Comment by joshowen** [comment]
Hey @sesh and @NielsZeilemaker 

I gave this a test and ran into some issues.  
- the conda entry for `python` has no date attribute
- `-e` entries don't contain `==`

Here is an example environment.yml file that exhibits them:
```yaml
name: TestEnv
channels:
  - defaults
  - conda-forge
dependencies:
  - python=2.7.13
  - Bottleneck=1.2.0
  - pip:
    - amqp==2.1.4
    - analytics-python==1.2.6
    - "-egit+https://github.com/joshowen/django-debug-toolbar-redis.git@794974207e9aa15f797a5de1c9636998195b6a94#egg=django-debug-toolbar-redis"
    - django-extensions==1.7.5
```

**Comment by NielsZeilemaker** [comment]
Hi @joshowen, thanks for the environment.yml file, I've fixed the code to support these "edge" cases.

**Comment by joshowen** [comment]
@sesh Any thoughts on merging this in?

**Comment by joshowen** [comment]
hey @sesh any thoughts on merging this in?  It would be useful for our organization if we could remove our duplicated requirements.txt files

**Pull request closed without merging**
